//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear clipboard in {0} seconds..
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_0 {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear clipboard in 1 second..
        /// </summary>
        public static string AUTO_CLEAR_CLIPBOARD_IN_ONE {
            get {
                return ResourceManager.GetString("AUTO_CLEAR_CLIPBOARD_IN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide password in {0} seconds..
        /// </summary>
        public static string AUTO_HIDE_IN_0 {
            get {
                return ResourceManager.GetString("AUTO_HIDE_IN_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide password in 1 second..
        /// </summary>
        public static string AUTO_HIDE_IN_ONE {
            get {
                return ResourceManager.GetString("AUTO_HIDE_IN_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Cancel.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _OK.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _About....
        /// </summary>
        public static string CMD_ABOUT {
            get {
                return ResourceManager.GetString("CMD_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Add....
        /// </summary>
        public static string CMD_ADD {
            get {
                return ResourceManager.GetString("CMD_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change _key directory....
        /// </summary>
        public static string CMD_CHANGE_KEY_DIRECTORY {
            get {
                return ResourceManager.GetString("CMD_CHANGE_KEY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change _master password....
        /// </summary>
        public static string CMD_CHANGE_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_CHANGE_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Close.
        /// </summary>
        public static string CMD_CLOSE {
            get {
                return ResourceManager.GetString("CMD_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy _login to clipboard.
        /// </summary>
        public static string CMD_COPY_LOGIN {
            get {
                return ResourceManager.GetString("CMD_COPY_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy _password to clipboard.
        /// </summary>
        public static string CMD_COPY_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_COPY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Remove.
        /// </summary>
        public static string CMD_DELETE {
            get {
                return ResourceManager.GetString("CMD_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Edit....
        /// </summary>
        public static string CMD_EDIT {
            get {
                return ResourceManager.GetString("CMD_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E_xit.
        /// </summary>
        public static string CMD_EXIT {
            get {
                return ResourceManager.GetString("CMD_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start password _generator.
        /// </summary>
        public static string CMD_GENERATE_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_GENERATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на H_ide password.
        /// </summary>
        public static string CMD_HIDE_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_HIDE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cards.
        /// </summary>
        public static string CMD_HISTORY {
            get {
                return ResourceManager.GetString("CMD_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _New....
        /// </summary>
        public static string CMD_NEW {
            get {
                return ResourceManager.GetString("CMD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Open....
        /// </summary>
        public static string CMD_OPEN {
            get {
                return ResourceManager.GetString("CMD_OPEN", resourceCulture);
            }
        }
        
       
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Properties....
        /// </summary>
        public static string CMD_PROPERTIES {
            get {
                return ResourceManager.GetString("CMD_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Save.
        /// </summary>
        public static string CMD_SAVE {
            get {
                return ResourceManager.GetString("CMD_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save _As....
        /// </summary>
        public static string CMD_SAVE_AS {
            get {
                return ResourceManager.GetString("CMD_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Se_ttings....
        /// </summary>
        public static string CMD_SETTINGS {
            get {
                return ResourceManager.GetString("CMD_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show _login column.
        /// </summary>
        public static string CMD_SHOW_LOGIN_COLUMN {
            get {
                return ResourceManager.GetString("CMD_SHOW_LOGIN_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Show password.
        /// </summary>
        public static string CMD_SHOW_PASSWORD {
            get {
                return ResourceManager.GetString("CMD_SHOW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show pass_word column.
        /// </summary>
        public static string CMD_SHOW_PASSWORD_COLUMN {
            get {
                return ResourceManager.GetString("CMD_SHOW_PASSWORD_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show _toolbar.
        /// </summary>
        public static string CMD_SHOW_TOOLBAR {
            get {
                return ResourceManager.GetString("CMD_SHOW_TOOLBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string COLUMN_LOGIN {
            get {
                return ResourceManager.GetString("COLUMN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string COLUMN_PASSWORD {
            get {
                return ResourceManager.GetString("COLUMN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The selected file has the wrong format..
        /// </summary>
        public static string ERROR_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The key for &apos;{0}&apos; does not exist in the directory &apos;{1}&apos;..
        /// </summary>
        public static string ERROR_KEY_NOT_FOUND_0_1 {
            get {
                return ResourceManager.GetString("ERROR_KEY_NOT_FOUND_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred. {0}.
        /// </summary>
        public static string ERROR_OCCURRED_0 {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password does not match..
        /// </summary>
        public static string ERROR_PASSWORD_DOES_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_DOES_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password must contain at least 4 characters..
        /// </summary>
        public static string ERROR_PASSWORD_MIN_CHARS {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_MIN_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password is wrong..
        /// </summary>
        public static string ERROR_WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_WRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password files (*.pwd)|*.pwd|All files (*.*)|*.*.
        /// </summary>
        public static string FILE_DIALOG_FILTER {
            get {
                return ResourceManager.GetString("FILE_DIALOG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C_lear clipboard after (seconds):.
        /// </summary>
        public static string LABEL_AUTO_CLEAR_CLIPBOARD {
            get {
                return ResourceManager.GetString("LABEL_AUTO_CLEAR_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Hide password after (seconds):.
        /// </summary>
        public static string LABEL_AUTO_HIDE_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_AUTO_HIDE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock window automatically.
        /// </summary>
        public static string LABEL_AUTOLOCK {
            get {
                return ResourceManager.GetString("LABEL_AUTOLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на and minimize window.
        /// </summary>
        public static string LABEL_AUTOMINIMIZE {
            get {
                return ResourceManager.GetString("LABEL_AUTOMINIMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm m_aster password:.
        /// </summary>
        public static string LABEL_CONFIRM_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C_onfirm new master password:.
        /// </summary>
        public static string LABEL_CONFIRM_NEW_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_NEW_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm passw_ord:.
        /// </summary>
        public static string LABEL_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Description:.
        /// </summary>
        public static string LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the master password for &apos;{0}&apos;..
        /// </summary>
        public static string LABEL_ENTER_MASTER_PASSWORD_FOR_0 {
            get {
                return ResourceManager.GetString("LABEL_ENTER_MASTER_PASSWORD_FOR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key:.
        /// </summary>
        public static string LABEL_KEY {
            get {
                return ResourceManager.GetString("LABEL_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key d_irectory:.
        /// </summary>
        public static string LABEL_KEY_DIRECTORY {
            get {
                return ResourceManager.GetString("LABEL_KEY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Login:.
        /// </summary>
        public static string LABEL_LOGIN {
            get {
                return ResourceManager.GetString("LABEL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Master password:.
        /// </summary>
        public static string LABEL_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Name:.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _New master password:.
        /// </summary>
        public static string LABEL_NEW_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_NEW_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C_urrent master password:.
        /// </summary>
        public static string LABEL_OLD_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_OLD_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Password:.
        /// </summary>
        public static string LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password _file:.
        /// </summary>
        public static string LABEL_PASSWORD_FILE {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Reenter password after (seconds):.
        /// </summary>
        public static string LABEL_REENTER_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_REENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select key directory..
        /// </summary>
        public static string LABEL_SELECT_KEY_DIRECTORY {
            get {
                return ResourceManager.GetString("LABEL_SELECT_KEY_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show _windows always in front.
        /// </summary>
        public static string LABEL_TOPMOST {
            get {
                return ResourceManager.GetString("LABEL_TOPMOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _URL:.
        /// </summary>
        public static string LABEL_URL {
            get {
                return ResourceManager.GetString("LABEL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Edit.
        /// </summary>
        public static string MENUITEM_EDIT {
            get {
                return ResourceManager.GetString("MENUITEM_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _File.
        /// </summary>
        public static string MENUITEM_FILE {
            get {
                return ResourceManager.GetString("MENUITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        public static string MENUITEM_HELP {
            get {
                return ResourceManager.GetString("MENUITEM_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _View.
        /// </summary>
        public static string MENUITEM_VIEW {
            get {
                return ResourceManager.GetString("MENUITEM_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to delete the selected items?.
        /// </summary>
        public static string QUESTION_DELETE_ITEMS {
            get {
                return ResourceManager.GetString("QUESTION_DELETE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save the changes?.
        /// </summary>
        public static string QUESTION_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("QUESTION_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} of {1} items selected..
        /// </summary>
        public static string SELECTED_0_OF_1 {
            get {
                return ResourceManager.GetString("SELECTED_0_OF_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 item selected..
        /// </summary>
        public static string SELECTED_ONE {
            get {
                return ResourceManager.GetString("SELECTED_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copyright 2017 Niels Stockfleth
        ///
        ///This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details..
        /// </summary>
        public static string TEXT_COPYRIGHT {
            get {
                return ResourceManager.GetString("TEXT_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search list.
        /// </summary>
        public static string TEXT_SEARCH_LIST {
            get {
                return ResourceManager.GetString("TEXT_SEARCH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string TITLE_ADD {
            get {
                return ResourceManager.GetString("TITLE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change master password.
        /// </summary>
        public static string TITLE_CHANGE_MASTER_PASSWORD {
            get {
                return ResourceManager.GetString("TITLE_CHANGE_MASTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string TITLE_EDIT {
            get {
                return ResourceManager.GetString("TITLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New password file.
        /// </summary>
        public static string TITLE_NEW {
            get {
                return ResourceManager.GetString("TITLE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password Manager.
        /// </summary>
        public static string TITLE_PASSWORD_MANAGER {
            get {
                return ResourceManager.GetString("TITLE_PASSWORD_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        public static string TITLE_PROPERTIES {
            get {
                return ResourceManager.GetString("TITLE_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string TITLE_SETTINGS {
            get {
                return ResourceManager.GetString("TITLE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string TOOLTIP_ADD {
            get {
                return ResourceManager.GetString("TOOLTIP_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy login to clipboard.
        /// </summary>
        public static string TOOLTIP_COPY_LOGIN {
            get {
                return ResourceManager.GetString("TOOLTIP_COPY_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy password to clipboard.
        /// </summary>
        public static string TOOLTIP_COPY_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_COPY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string TOOLTIP_DELETE {
            get {
                return ResourceManager.GetString("TOOLTIP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string TOOLTIP_EDIT {
            get {
                return ResourceManager.GetString("TOOLTIP_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start password generator.
        /// </summary>
        public static string TOOLTIP_GENERATE_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_GENERATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide password.
        /// </summary>
        public static string TOOLTIP_HIDE_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_HIDE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string TOOLTIP_NEW {
            get {
                return ResourceManager.GetString("TOOLTIP_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string TOOLTIP_OPEN {
            get {
                return ResourceManager.GetString("TOOLTIP_OPEN", resourceCulture);
            }
        }
        
     
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string TOOLTIP_SAVE {
            get {
                return ResourceManager.GetString("TOOLTIP_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show password.
        /// </summary>
        public static string TOOLTIP_SHOW_PASSWORD {
            get {
                return ResourceManager.GetString("TOOLTIP_SHOW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} items..
        /// </summary>
        public static string TOTAL_0 {
            get {
                return ResourceManager.GetString("TOTAL_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 item..
        /// </summary>
        public static string TOTAL_ONE {
            get {
                return ResourceManager.GetString("TOTAL_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verify password.
        /// </summary>
        public static string VERIFY_PASSWORD {
            get {
                return ResourceManager.GetString("VERIFY_PASSWORD", resourceCulture);
            }
        }
    }
}
